apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-detector
  labels:
    app: motion-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motion-detector
  template:
    metadata:
      labels:
        app: motion-detector
    spec:
      containers:
      - name: motion-detector
        image: your-docker-image:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: VIDEO_URL
          value: "http://raspi43.local:8080/?action=stream"